### ISSUE TITLE
Unable to upload photos due to daa08c6

### ISSUE THREAD

**Issue by yamanq** [Piwigo/piwigo-flutter-app#106]
Android 11, Pixel 4a, version is current master (f747221) +  #103 
After taking a photo and clicking the upload button, it fails to upload with the trace below. Notably, I can still do other actions, such as create and delete an album. I tried the same version on Android 11, Pixel 2 and was also unable to upload.

Using git bisect, I was able to isolate the bad commit to daa08c6 on both devices.

```
I/flutter (26805): DioError [DioErrorType.response]: Http status error [401]
I/flutter (26805): Source stack:
I/flutter (26805): #0      DioMixin.fetch (package:dio/src/dio_mixin.dart:473:35)
I/flutter (26805): #1      DioMixin.request (package:dio/src/dio_mixin.dart:468:12)
I/flutter (26805): #2      UploadRequest.upload (package:piwigo_ng/services/upload/chunked_uploader.dart:100:35)
I/flutter (26805): <asynchronous suspension>
I/flutter (26805): #3      Uploader.uploadChunk (package:piwigo_ng/services/upload/Uploader.dart:162:14)
I/flutter (26805): <asynchronous suspension>
I/flutter (26805): #4      Uploader.uploadPhotos (package:piwigo_ng/services/upload/Uploader.dart:66:29)
I/flutter (26805): <asynchronous suspension>
I/flutter (26805): #5      _UploadGalleryViewPage.onUpload (package:piwigo_ng/views/UploadGalleryViewPage.dart:141:5)
I/flutter (26805): <asynchronous suspension>
I/flutter (26805): 0.28297372288632305
I/flutter (26805): 0.28300145270283655
I/flutter (26805): 0.28300201861745927
I/flutter (26805): 0.2830031504467047
I/flutter (26805): 0.2830195619707637
I/flutter (26805): 0.2830467258726545
I/flutter (26805): 0.2830472917872772
I/flutter (26805): 0.28304842361652266
I/flutter (26805): 0.28306483514058167
I/flutter (26805): 0.2830942627009634
I/flutter (26805): 0.28311237196889055
I/flutter (26805): 0.283113503798136
I/flutter (26805): 0.283129915322195
I/flutter (26805): 0.28316104062644487
I/flutter (26805): 0.28317914989437204
I/flutter (26805): 0.2831802817236175
I/flutter (26805): 0.2831966932476765
I/flutter (26805): 0.2832255548934354
I/flutter (26805): 0.28325894385617617
I/flutter (26805): 0.28326007568542166
I/flutter (26805): 0.2832764872094807
I/flutter (26805): 0.2833053488552396
I/flutter (26805): 0.28330704659910777
I/flutter (26805): 0.2833081784283532
I/flutter (26805): 0.2833245899524122
I/flutter (26805): 0.2833511879396803
I/flutter (26805): 0.2833534515981712
I/flutter (26805): 0.28335458342741665
I/flutter (26805): 0.28337099495147566
I/flutter (26805): 0.28346097537648884
I/flutter (26805): 0.3205487560913635
I/flutter (26805): 0.3576365368062382
I/flutter (26805): 0.39472431752111287
I/flutter (26805): 0.43181209823598754
I/flutter (26805): 0.4688998789508622
I/flutter (26805): 0.5059876596657369
I/flutter (26805): 0.5430754403806115
I/flutter (26805): 0.5664182867387528
I/flutter (26805): 0.5664194185679983
I/flutter (26805): 0.5664369619213028
I/flutter (26805): DioError [DioErrorType.response]: Http status error [401]
I/flutter (26805): Source stack:
I/flutter (26805): #0      DioMixin.fetch (package:dio/src/dio_mixin.dart:473:35)
I/flutter (26805): #1      DioMixin.request (package:dio/src/dio_mixin.dart:468:12)
I/flutter (26805): #2      UploadRequest.upload (package:piwigo_ng/services/upload/chunked_uploader.dart:100:35)
I/flutter (26805): <asynchronous suspension>
I/flutter (26805): #3      Uploader.uploadChunk (package:piwigo_ng/services/upload/Uploader.dart:162:14)
I/flutter (26805): <asynchronous suspension>
I/flutter (26805): #4      Uploader.uploadPhotos (package:piwigo_ng/services/upload/Uploader.dart:66:29)
I/flutter (26805): <asynchronous suspension>
I/flutter (26805): #5      _UploadGalleryViewPage.onUpload (package:piwigo_ng/views/UploadGalleryViewPage.dart:141:5)
I/flutter (26805): <asynchronous suspension>
I/flutter (26805): 0.565931034248587
I/flutter (26805): 0.5659587640651006
I/flutter (26805): 0.5659593299797233
I/flutter (26805): 0.5659604618089688
I/flutter (26805): 0.5659768733330277
I/flutter (26805): 0.5660040372349185
I/flutter (26805): 0.5660046031495413
I/flutter (26805): 0.5660057349787867
I/flutter (26805): 0.5660221465028457
I/flutter (26805): 0.5660515740632274
I/flutter (26805): 0.5660696833311546
I/flutter (26805): 0.5660708151604
I/flutter (26805): 0.566087226684459
I/flutter (26805): 0.5661183519887089
I/flutter (26805): 0.5661364612566361
I/flutter (26805): 0.5661375930858815
I/flutter (26805): 0.5661540046099405
I/flutter (26805): 0.5661828662556995
I/flutter (26805): 0.5662162552184402
I/flutter (26805): 0.5662173870476856
I/flutter (26805): 0.5662337985717447
I/flutter (26805): 0.5662626602175036
I/flutter (26805): 0.5662643579613718
I/flutter (26805): 0.5662654897906172
I/flutter (26805): 0.5662819013146763
I/flutter (26805): 0.5663084993019443
I/flutter (26805): 0.5663107629604353
I/flutter (26805): 0.5663118947896807
I/flutter (26805): 0.5663283063137396
I/flutter (26805): 0.5664182867387528
I/flutter (26805): 0.6035060674536276
I/flutter (26805): 0.6405938481685022
I/flutter (26805): 0.6776816288833769
I/flutter (26805): 0.7147694095982515
I/flutter (26805): 0.7518571903131263
I/flutter (26805): 0.7889449710280009
I/flutter (26805): 0.8260327517428756
I/flutter (26805): 0.8493755981010169
I/flutter (26805): 0.8493767299302624
I/flutter (26805): 0.8493942732835668
I/flutter (26805): DioError [DioErrorType.response]: Http status error [401]
I/flutter (26805): Source stack:
I/flutter (26805): #0      DioMixin.fetch (package:dio/src/dio_mixin.dart:473:35)
I/flutter (26805): #1      DioMixin.request (package:dio/src/dio_mixin.dart:468:12)
I/flutter (26805): #2      UploadRequest.upload (package:piwigo_ng/services/upload/chunked_uploader.dart:100:35)
I/flutter (26805): <asynchronous suspension>
I/flutter (26805): #3      Uploader.uploadChunk (package:piwigo_ng/services/upload/Uploader.dart:162:14)
I/flutter (26805): <asynchronous suspension>
I/flutter (26805): #4      Uploader.uploadPhotos (package:piwigo_ng/services/upload/Uploader.dart:66:29)
I/flutter (26805): <asynchronous suspension>
I/flutter (26805): #5      _UploadGalleryViewPage.onUpload (package:piwigo_ng/views/UploadGalleryViewPage.dart:141:5)
I/flutter (26805): <asynchronous suspension>
I/flutter (26805): 0.848888345610851
I/flutter (26805): 0.8489160754273646
I/flutter (26805): 0.8489166413419873
I/flutter (26805): 0.8489177731712327
I/flutter (26805): 0.8489341846952918
I/flutter (26805): 0.8489613485971825
I/flutter (26805): 0.8489619145118052
I/flutter (26805): 0.8489630463410507
I/flutter (26805): 0.8489794578651098
I/flutter (26805): 0.8490088854254914
I/flutter (26805): 0.8490269946934186
I/flutter (26805): 0.849028126522664
I/flutter (26805): 0.8490445380467231
I/flutter (26805): 0.8490756633509728
I/flutter (26805): 0.8490937726189001
I/flutter (26805): 0.8490949044481455
I/flutter (26805): 0.8491113159722046
I/flutter (26805): 0.8491401776179635
I/flutter (26805): 0.8491735665807042
I/flutter (26805): 0.8491746984099496
I/flutter (26805): 0.8491911099340087
I/flutter (26805): 0.8492199715797677
I/flutter (26805): 0.8492216693236359
I/flutter (26805): 0.8492228011528813
I/flutter (26805): 0.8492392126769402
I/flutter (26805): 0.8492658106642084
I/flutter (26805): 0.8492680743226992
I/flutter (26805): 0.8492692061519447
I/flutter (26805): 0.8492856176760037
I/flutter (26805): 0.8493755981010169
I/flutter (26805): 0.8864633788158915
I/flutter (26805): 0.9235511595307663
I/flutter (26805): 0.9606389402456409
I/flutter (26805): 0.9977267209605156
I/flutter (26805): 1.0005036640142249
I/flutter (26805): 1.0005047958434703
I/flutter (26805): 1.0005223391967748
I/flutter (26805): DioError [DioErrorType.response]: Http status error [401]
I/flutter (26805): Source stack:
I/flutter (26805): #0      DioMixin.fetch (package:dio/src/dio_mixin.dart:473:35)
I/flutter (26805): #1      DioMixin.request (package:dio/src/dio_mixin.dart:468:12)
I/flutter (26805): #2      UploadRequest.upload (package:piwigo_ng/services/upload/chunked_uploader.dart:100:35)
I/flutter (26805): <asynchronous suspension>
I/flutter (26805): #3      Uploader.uploadChunk (package:piwigo_ng/services/upload/Uploader.dart:162:14)
I/flutter (26805): <asynchronous suspension>
I/flutter (26805): #4      Uploader.uploadPhotos (package:piwigo_ng/services/upload/Uploader.dart:66:29)
I/flutter (26805): <asynchronous suspension>
I/flutter (26805): #5      _UploadGalleryViewPage.onUpload (package:piwigo_ng/views/UploadGalleryViewPage.dart:141:5)
I/flutter (26805): <asynchronous suspension>
E/flutter (26805): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: NoSuchMethodError: The getter 'data' was called on null.
E/flutter (26805): Receiver: null
E/flutter (26805): Tried calling: data
E/flutter (26805): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
E/flutter (26805): #1      Uploader.uploadPhotos (package:piwigo_ng/services/upload/Uploader.dart:72:41)
E/flutter (26805): <asynchronous suspension>
E/flutter (26805): #2      _UploadGalleryViewPage.onUpload (package:piwigo_ng/views/UploadGalleryViewPage.dart:141:5)
E/flutter (26805): <asynchronous suspension>
E/flutter (26805): 
```

**Comment by yamanq** [comment]
Fixed by e8bbc2471912bf2a86fe414b9885a593ca938f53
