### ISSUE TITLE
NoSuchMethodError tapping on an album

### ISSUE THREAD

**Issue by jspam** [Piwigo/piwigo-flutter-app#50]
Using piwigo_ng-0.0.10.1-beta, when tapping on an album, nothing happens (the album is not opened).

Building from source in Debug mode, I get the following backtrace:
```
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown while handling a gesture:
The method 'call' was called on null.
Receiver: null
Tried calling: call()

When the exception was thrown, this was the stack:
#0      _AlbumListItemState.build.<anonymous closure> (package:piwigo_ng/views/components/list_item.dart:128:22)
#1      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
#2      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
#3      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608:11)
#4      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
#5      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:267:7)
#6      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
#7      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:443:20)
#8      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
#9      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:308:11)
#10     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#11     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#12     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#13     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#17     _invoke1 (dart:ui/hooks.dart:169:10)
#18     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#19     _dispatchPointerDataPacket (dart:ui/hooks.dart:88:31)
(elided 3 frames from dart:async)

Handler: "onTap"
Recognizer:
  TapGestureRecognizer#3fec9
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by jspam** [comment]
I bisected it down to 802b2096bcd523a5d00332d0fda212356499e48a
